# Copyright (c) Ansible Project
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

# https://coverage.readthedocs.io/en/latest/config.html

[report]
# https://coverage.readthedocs.io/en/latest/excluding.html
exclude_also = [
    "if t\\.TYPE_CHECKING:",
]
