# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: community
name: dns
version: 0.1.0
readme: README.md
authors:
  - Felix Fontein (github.com/felixfontein)
description: Plugins and modules for working with DNS
license_file: COPYING
tags:
  - community
  - dns
repository: https://github.com/ansible-collections/community.dns
#documentation: https://github.com/ansible-collection-migration/community.dns/tree/main/docs
homepage: https://github.com/ansible-collections/community.dns
issues: https://github.com/ansible-collections/community.dns/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
