---
# Copyright (c) Ansible Project
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: community
name: dns
version: 2.6.4
readme: README.md
authors:
  - Felix Fontein (github.com/felixfontein)
  - Markus Bergholz (github.com/markuman)
description: Plugins and modules for working with DNS
license:
  - GPL-3.0-or-later
  - MPL-2.0
#license_file: COPYING
tags:
  - community
  - dns
  - hosttech
  - hetzner
repository: https://github.com/ansible-collections/community.dns
documentation: https://docs.ansible.com/ansible/devel/collections/community/dns/
homepage: https://github.com/ansible-collections/community.dns
issues: https://github.com/ansible-collections/community.dns/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
  - tests/integration/integration_config.yml
