# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: community
name: dns
version: 1.2.0
readme: README.md
authors:
  - Felix Fontein (github.com/felixfontein)
description: Plugins and modules for working with DNS
license:
  - GPL-3.0-or-later
  - MPL-2.0
#license_file: COPYING
tags:
  - community
  - dns
  - hosttech
repository: https://github.com/ansible-collections/community.dns
documentation: https://ansible.fontein.de/collections/community/dns/
homepage: https://github.com/ansible-collections/community.dns
issues: https://github.com/ansible-collections/community.dns/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
  - tests/integration/integration_config.yml
