# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2025 Felix Fontein <felix@fontein.de>

line-length = 160

[lint]
# https://docs.astral.sh/ruff/rules/

select = ["A", "B", "E", "F", "FA", "FLY", "UP", "SIM"]
ignore = [
    # Needed:
    "E402",  # Module level import not at top of file
    "F401",  # Unused import (ruff check doesn't notice type comments apparently)
    # TODO:
    "SIM117",  # Combine multiple 'with' statements
    # Dubious:
    "SIM105",  # suppressible-exception
    "UP012",  # Unnecessary call to `encode` as UTF-8
    "UP015",  # Unnecessary mode argument
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed or starting with dummy
dummy-variable-rgx = "^(_|dummy).*$"

[lint.isort]
known-third-party = [
    "ansible_collections.community.internal_test_tools",
    "ansible_collections.community.library_inventory_filtering_v1",
]
