---
# Copyright (c) Ansible Project
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

name: nox
'on':
  push:
    branches:
      - main
      - stable-*
  pull_request:
  # Run CI once per day (at 04:30 UTC)
  schedule:
    - cron: '30 4 * * *'
  workflow_dispatch:

jobs:
  nox:
    runs-on: ubuntu-latest
    name: "Run nox"
    steps:
      - name: Check out collection
        uses: actions/checkout@v4
        with:
          path: ansible_collections/community/dns
          persist-credentials: false
      - name: Check out dependent collections
        run: >-
          ansible-galaxy collection install -p .
          git+https://github.com/ansible-collections/community.internal_test_tools.git,main
          git+https://github.com/ansible-collections/community.library_inventory_filtering.git,stable-1
      - name: Run nox
        uses: ansible-community/antsibull-nox@main
        with:
          working-directory: ansible_collections/community/dns

  sanity:
    name: Sanity (Ⓐ${{ matrix.ansible }})
    strategy:
      matrix:
        include:
          - ansible: "2.14"
            python: "3.11"
          - ansible: "2.15"
            python: "3.11"
          - ansible: "2.16"
            python: "3.12"
          - ansible: "2.17"
            python: "3.12"
          - ansible: "2.18"
            python: "3.13"
          - ansible: devel
            python: "3.13"
    runs-on: ubuntu-latest
    steps:
      - name: Check out collection
        uses: actions/checkout@v4
        with:
          path: ansible_collections/community/dns
          persist-credentials: false
      - name: Check out dependent collections
        run: >-
          ansible-galaxy collection install -p .
          git+https://github.com/ansible-collections/community.library_inventory_filtering.git,stable-1
      - name: Run nox
        uses: ansible-community/antsibull-nox@main
        with:
          working-directory: ansible_collections/community/dns
          extra-python-versions: ${{ matrix.python }}
          sessions: ansible-test-sanity-${{ matrix.ansible }}

  units:
    name: Units (Ⓐ${{ matrix.ansible }})
    strategy:
      matrix:
        include:
          - ansible: "2.14"
            python: "3.11"
          - ansible: "2.15"
            python: "3.11"
          - ansible: "2.16"
            python: "3.12"
          - ansible: "2.17"
            python: "3.12"
          - ansible: "2.18"
            python: "3.13"
          - ansible: devel
            python: "3.13"
    runs-on: ubuntu-latest
    steps:
      - name: Check out collection
        uses: actions/checkout@v4
        with:
          path: ansible_collections/community/dns
          persist-credentials: false
      - name: Check out dependent collections
        run: >-
          ansible-galaxy collection install -p .
          git+https://github.com/ansible-collections/community.internal_test_tools.git,main
          git+https://github.com/ansible-collections/community.library_inventory_filtering.git,stable-1
      - name: Run nox
        uses: ansible-community/antsibull-nox@main
        with:
          working-directory: ansible_collections/community/dns
          extra-python-versions: ${{ matrix.python }}
          sessions: ansible-test-units-${{ matrix.ansible }}

  integration:
    name: I (Ⓐ${{ matrix.ansible }}+py${{ matrix.python }})
    strategy:
      fail-fast: false
      matrix:
        ansible:
          - devel
        python:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
        ansible_python:
          - "3.13"
        include:
          # 2.14
          - ansible: "2.14"
            python: "2.7"
            ansible_python: "3.11"
          - ansible: "2.14"
            python: "3.5"
            ansible_python: "3.11"
          - ansible: "2.14"
            python: "3.9"
            ansible_python: "3.11"
          # 2.15
          - ansible: "2.15"
            python: "3.7"
            ansible_python: "3.11"
          # 2.16
          - ansible: "2.16"
            python: "2.7"
            ansible_python: "3.12"
          - ansible: "2.16"
            python: "3.6"
            ansible_python: "3.12"
          - ansible: "2.16"
            python: "3.11"
            ansible_python: "3.12"
          # 2.17
          - ansible: "2.17"
            python: "3.7"
            ansible_python: "3.12"
          - ansible: "2.17"
            python: "3.12"
            ansible_python: "3.12"
          # 2.18
          - ansible: "2.18"
            python: "3.8"
            ansible_python: "3.13"
          - ansible: "2.18"
            python: "3.13"
            ansible_python: "3.13"

    runs-on: ubuntu-latest
    steps:
      - name: Check out collection
        uses: actions/checkout@v4
        with:
          path: ansible_collections/community/dns
          persist-credentials: false
      - name: Check out dependent collections
        run: >-
          ansible-galaxy collection install -p .
          git+https://github.com/ansible-collections/community.general.git,main
          git+https://github.com/ansible-collections/community.library_inventory_filtering.git,stable-1
      - name: Run nox
        uses: ansible-community/antsibull-nox@main
        with:
          working-directory: ansible_collections/community/dns
          extra-python-versions: ${{ matrix.ansible_python }}
          sessions: ansible-test-integration-${{ matrix.ansible }}-${{ matrix.python }}
